title: James D. Schmidt
url: https://jamesdschmidt.com
twitter_username: jamesdschmidt
github_username: jamesdschmidt

theme: minima
plugins:
  - jekyll-feed

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  
minima:
  social_links:
    twitter: jamesdschmidt
    github: jamesdschmidt

header_pages:
  - about.md

google_analytics: UA-56785727-1

show_exerpts: true

include: ["_pages"]

site:
  og_image: /assets/images/site-logo.jpeg

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
