title: James D. Schmidt
description: microservices, Spring, Java
url: https://jamesdschmidt.com
email: "james.daniel.schmidt@gmail.com"
twitter_username: jamesdschmidt
github_username: jamesdschmidt

theme: minima
plugins:
  - jekyll-feed

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

permalink: /:title

header_pages:
  - about.md
  - what-i-use.md
  - what-im-reading.md

google_analytics: UA-56785727-1

show_exerpts: true

site:
  og_image: /assets/images/site-logo.jpeg
