title: James D. Schmidt
name: "James D. Schmidt"
url: "https://jamesdschmidt.com"
repository: "jamesdschmidt/jamesdschmidt.github.io"
timezone: America/Denver

remote_theme: "mmistakes/minimal-mistakes@4.18.1"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-56785727-1"
